name: qu2s
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firedart: ^0.9.1+1
  dart_date: ^1.1.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Fira code
      fonts:
        - asset: fonts/FiraCode-Light.ttf
          weight: 300
        - asset: fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: fonts/FiraCode-Bold.ttf
          weight: 700