// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkO05UO2PHQvgfAnobGZjmhpa6-yrtm-I',
    appId: '1:420780234622:web:7fc5e6e71aa7aa3ed1452f',
    messagingSenderId: '420780234622',
    projectId: 'qu2s-596fc',
    authDomain: 'qu2s-596fc.firebaseapp.com',
    storageBucket: 'qu2s-596fc.appspot.com',
    measurementId: 'G-9PML7K0TD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTcCzF-zzwRfg5h9pOQh1vxXXwYg3_vnw',
    appId: '1:420780234622:android:c210da89515d3f9fd1452f',
    messagingSenderId: '420780234622',
    projectId: 'qu2s-596fc',
    storageBucket: 'qu2s-596fc.appspot.com',
  );
}
